import { IUser } from './interfaces/user.interface'

export const USERS: IUser[] = [
  {
    id: '1',
    name: 'Alice',
    interests: ['hiking', 'movies', 'reading'],
    readinessScore: 8,
    gender: 'female',
    genderPreference: ['male'],
  },
  {
    id: '2',
    name: 'Bob',
    interests: ['movies', 'music', 'cooking'],
    readinessScore: 7,
    gender: 'male',
    genderPreference: ['female'],
  },
  {
    id: '3',
    name: 'Charlie',
    interests: ['hiking', 'gaming', 'coding'],
    readinessScore: 6,
    gender: 'male',
    genderPreference: ['male'],
  },
  {
    id: '4',
    name: 'Diana',
    interests: ['reading', 'music', 'hiking'],
    readinessScore: 9,
    gender: 'female',
    genderPreference: ['male'],
  },
  {
    id: '5',
    name: 'Eve',
    interests: ['dancing', 'painting', 'traveling'],
    readinessScore: 5,
    gender: 'female',
    genderPreference: ['male', 'female'],
  },
  {
    id: '6',
    name: 'Frank',
    interests: ['photography', 'running', 'gaming'],
    readinessScore: 7,
    gender: 'male',
    genderPreference: ['male', 'female'],
  },
  {
    id: '7',
    name: 'Grace',
    interests: ['cooking', 'hiking', 'movies'],
    readinessScore: 6,
    gender: 'female',
    genderPreference: ['female'],
  },
  {
    id: '8',
    name: 'Hank',
    interests: ['gaming', 'coding', 'movies'],
    readinessScore: 8,
    gender: 'male',
    genderPreference: ['female'],
  },
  {
    id: '9',
    name: 'Ivy',
    interests: ['reading', 'movies', 'traveling'],
    readinessScore: 9,
    gender: 'female',
    genderPreference: ['male'],
  },
  {
    id: '10',
    name: 'Jack',
    interests: ['hiking', 'music', 'photography'],
    readinessScore: 5,
    gender: 'male',
    genderPreference: ['male'],
  },
  {
    id: '11',
    name: 'Kara',
    interests: ['painting', 'gaming', 'cooking'],
    readinessScore: 7,
    gender: 'female',
    genderPreference: ['male', 'female'],
  },
  {
    id: '12',
    name: 'Liam',
    interests: ['running', 'movies', 'coding'],
    readinessScore: 8,
    gender: 'male',
    genderPreference: ['female'],
  },
  {
    id: '13',
    name: 'Mia',
    interests: ['traveling', 'dancing', 'music'],
    readinessScore: 6,
    gender: 'female',
    genderPreference: ['female'],
  },
  {
    id: '14',
    name: 'Nate',
    interests: ['photography', 'reading', 'gaming'],
    readinessScore: 7,
    gender: 'male',
    genderPreference: ['male', 'female'],
  },
  {
    id: '15',
    name: 'Olivia',
    interests: ['hiking', 'coding', 'movies'],
    readinessScore: 9,
    gender: 'female',
    genderPreference: ['male'],
  },
  {
    id: '16',
    name: 'Paul',
    interests: ['gaming', 'music', 'traveling'],
    readinessScore: 5,
    gender: 'male',
    genderPreference: ['male'],
  },
  {
    id: '17',
    name: 'Quinn',
    interests: ['movies', 'dancing', 'painting'],
    readinessScore: 7,
    gender: 'non-binary',
    genderPreference: ['male', 'female'],
  },
  {
    id: '18',
    name: 'Rachel',
    interests: ['running', 'hiking', 'photography'],
    readinessScore: 8,
    gender: 'female',
    genderPreference: ['female'],
  },
  {
    id: '19',
    name: 'Sam',
    interests: ['coding', 'reading', 'gaming'],
    readinessScore: 6,
    gender: 'male',
    genderPreference: ['male', 'female'],
  },
  {
    id: '20',
    name: 'Tina',
    interests: ['music', 'movies', 'cooking'],
    readinessScore: 9,
    gender: 'female',
    genderPreference: ['male'],
  },
  {
    id: '21',
    name: 'Uma',
    interests: ['traveling', 'painting', 'running'],
    readinessScore: 7,
    gender: 'female',
    genderPreference: ['female'],
  },
  {
    id: '22',
    name: 'Vince',
    interests: ['gaming', 'photography', 'coding'],
    readinessScore: 5,
    gender: 'male',
    genderPreference: ['female'],
  },
  {
    id: '23',
    name: 'Wendy',
    interests: ['reading', 'music', 'dancing'],
    readinessScore: 8,
    gender: 'female',
    genderPreference: ['male', 'female'],
  },
  {
    id: '24',
    name: 'Xander',
    interests: ['movies', 'hiking', 'gaming'],
    readinessScore: 6,
    gender: 'male',
    genderPreference: ['male'],
  },
  {
    id: '25',
    name: 'Yara',
    interests: ['painting', 'coding', 'traveling'],
    readinessScore: 9,
    gender: 'female',
    genderPreference: ['male'],
  },
  {
    id: '26',
    name: 'Zane',
    interests: ['gaming', 'movies', 'photography'],
    readinessScore: 5,
    gender: 'male',
    genderPreference: ['male', 'female'],
  },
  {
    id: '27',
    name: 'Amy',
    interests: ['dancing', 'music', 'cooking'],
    readinessScore: 7,
    gender: 'female',
    genderPreference: ['male'],
  },
  {
    id: '28',
    name: 'Brian',
    interests: ['hiking', 'movies', 'gaming'],
    readinessScore: 6,
    gender: 'male',
    genderPreference: ['male'],
  },
  {
    id: '29',
    name: 'Cathy',
    interests: ['reading', 'painting', 'photography'],
    readinessScore: 8,
    gender: 'female',
    genderPreference: ['male', 'female'],
  },
  {
    id: '30',
    name: 'David',
    interests: ['coding', 'music', 'movies'],
    readinessScore: 7,
    gender: 'male',
    genderPreference: ['female'],
  },
  {
    id: '31',
    name: 'Ella',
    interests: ['hiking', 'running', 'traveling'],
    readinessScore: 9,
    gender: 'female',
    genderPreference: ['female'],
  },
  {
    id: '32',
    name: 'Felix',
    interests: ['gaming', 'coding', 'photography'],
    readinessScore: 6,
    gender: 'male',
    genderPreference: ['male', 'female'],
  },
  {
    id: '33',
    name: 'Gina',
    interests: ['movies', 'music', 'dancing'],
    readinessScore: 8,
    gender: 'female',
    genderPreference: ['male'],
  },
  {
    id: '34',
    name: 'Henry',
    interests: ['reading', 'hiking', 'gaming'],
    readinessScore: 7,
    gender: 'male',
    genderPreference: ['male'],
  },
  {
    id: '35',
    name: 'Isla',
    interests: ['painting', 'coding', 'traveling'],
    readinessScore: 5,
    gender: 'female',
    genderPreference: ['male', 'female'],
  },
  {
    id: '36',
    name: 'Jake',
    interests: ['music', 'movies', 'photography'],
    readinessScore: 9,
    gender: 'male',
    genderPreference: ['female'],
  },
  {
    id: '37',
    name: 'Katy',
    interests: ['hiking', 'dancing', 'cooking'],
    readinessScore: 6,
    gender: 'female',
    genderPreference: ['female'],
  },
  {
    id: '38',
    name: 'Luke',
    interests: ['coding', 'gaming', 'traveling'],
    readinessScore: 8,
    gender: 'male',
    genderPreference: ['male', 'female'],
  },
  {
    id: '39',
    name: 'Mona',
    interests: ['music', 'reading', 'movies'],
    readinessScore: 7,
    gender: 'female',
    genderPreference: ['male'],
  },
  {
    id: '40',
    name: 'Nolan',
    interests: ['hiking', 'gaming', 'photography'],
    readinessScore: 6,
    gender: 'male',
    genderPreference: ['male'],
  },
  {
    id: '41',
    name: 'Opal',
    interests: ['painting', 'coding', 'dancing'],
    readinessScore: 5,
    gender: 'female',
    genderPreference: ['male', 'female'],
  },
  {
    id: '42',
    name: 'Peter',
    interests: ['movies', 'music', 'traveling'],
    readinessScore: 9,
    gender: 'male',
    genderPreference: ['female'],
  },
  {
    id: '43',
    name: 'Quincy',
    interests: ['gaming', 'reading', 'hiking'],
    readinessScore: 8,
    gender: 'non-binary',
    genderPreference: ['male'],
  },
  {
    id: '44',
    name: 'Rita',
    interests: ['dancing', 'painting', 'coding'],
    readinessScore: 7,
    gender: 'female',
    genderPreference: ['male', 'female'],
  },
  {
    id: '45',
    name: 'Steve',
    interests: ['photography', 'movies', 'music'],
    readinessScore: 6,
    gender: 'male',
    genderPreference: ['female'],
  },
  {
    id: '46',
    name: 'Tara',
    interests: ['hiking', 'gaming', 'reading'],
    readinessScore: 5,
    gender: 'female',
    genderPreference: ['female'],
  },
  {
    id: '47',
    name: 'Ulysses',
    interests: ['coding', 'dancing', 'music'],
    readinessScore: 9,
    gender: 'male',
    genderPreference: ['male', 'female'],
  },
  {
    id: '48',
    name: 'Vera',
    interests: ['traveling', 'painting', 'movies'],
    readinessScore: 7,
    gender: 'female',
    genderPreference: ['male'],
  },
  {
    id: '49',
    name: 'Will',
    interests: ['gaming', 'photography', 'hiking'],
    readinessScore: 6,
    gender: 'male',
    genderPreference: ['male'],
  },
  {
    id: '50',
    name: 'Xena',
    interests: ['music', 'coding', 'traveling'],
    readinessScore: 5,
    gender: 'female',
    genderPreference: ['male', 'female'],
  },
  {
    id: '51',
    name: 'Yves',
    interests: ['movies', 'gaming', 'reading'],
    readinessScore: 8,
    gender: 'male',
    genderPreference: ['female'],
  },
  {
    id: '52',
    name: 'Zara',
    interests: ['dancing', 'painting', 'hiking'],
    readinessScore: 7,
    gender: 'female',
    genderPreference: ['female'],
  },
  {
    id: '53',
    name: 'Aaron',
    interests: ['music', 'traveling', 'coding'],
    readinessScore: 6,
    gender: 'male',
    genderPreference: ['male', 'female'],
  },
  {
    id: '54',
    name: 'Bella',
    interests: ['movies', 'photography', 'gaming'],
    readinessScore: 5,
    gender: 'female',
    genderPreference: ['male'],
  },
  {
    id: '55',
    name: 'Carl',
    interests: ['hiking', 'reading', 'painting'],
    readinessScore: 8,
    gender: 'male',
    genderPreference: ['male'],
  },
  {
    id: '56',
    name: 'Dana',
    interests: ['dancing', 'music', 'coding'],
    readinessScore: 7,
    gender: 'female',
    genderPreference: ['male', 'female'],
  },
  {
    id: '57',
    name: 'Ethan',
    interests: ['movies', 'gaming', 'traveling'],
    readinessScore: 9,
    gender: 'male',
    genderPreference: ['female'],
  },
  {
    id: '58',
    name: 'Fiona',
    interests: ['painting', 'music', 'dancing'],
    readinessScore: 6,
    gender: 'female',
    genderPreference: ['female'],
  },
  {
    id: '59',
    name: 'George',
    interests: ['gaming', 'reading', 'hiking'],
    readinessScore: 5,
    gender: 'male',
    genderPreference: ['male', 'female'],
  },
  {
    id: '60',
    name: 'Holly',
    interests: ['movies', 'photography', 'coding'],
    readinessScore: 7,
    gender: 'female',
    genderPreference: ['male'],
  },
  {
    id: '61',
    name: 'Ian',
    interests: ['hiking', 'music', 'traveling'],
    readinessScore: 8,
    gender: 'male',
    genderPreference: ['male'],
  },
  {
    id: '62',
    name: 'Jane',
    interests: ['gaming', 'reading', 'movies'],
    readinessScore: 6,
    gender: 'female',
    genderPreference: ['male', 'female'],
  },
  {
    id: '63',
    name: 'Kyle',
    interests: ['painting', 'dancing', 'photography'],
    readinessScore: 5,
    gender: 'male',
    genderPreference: ['female'],
  },
  {
    id: '64',
    name: 'Lara',
    interests: ['music', 'hiking', 'coding'],
    readinessScore: 7,
    gender: 'female',
    genderPreference: ['female'],
  },
  {
    id: '65',
    name: 'Mason',
    interests: ['gaming', 'traveling', 'movies'],
    readinessScore: 8,
    gender: 'male',
    genderPreference: ['male', 'female'],
  },
  {
    id: '66',
    name: 'Nina',
    interests: ['painting', 'reading', 'dancing'],
    readinessScore: 6,
    gender: 'female',
    genderPreference: ['male'],
  },
  {
    id: '67',
    name: 'Oscar',
    interests: ['music', 'movies', 'hiking'],
    readinessScore: 5,
    gender: 'male',
    genderPreference: ['male'],
  },
  {
    id: '68',
    name: 'Paula',
    interests: ['gaming', 'coding', 'traveling'],
    readinessScore: 9,
    gender: 'female',
    genderPreference: ['male', 'female'],
  },
  {
    id: '69',
    name: 'Quinton',
    interests: ['reading', 'photography', 'dancing'],
    readinessScore: 7,
    gender: 'male',
    genderPreference: ['female'],
  },
  {
    id: '70',
    name: 'Rosa',
    interests: ['hiking', 'music', 'movies'],
    readinessScore: 8,
    gender: 'female',
    genderPreference: ['female'],
  },
  {
    id: '71',
    name: 'Sean',
    interests: ['gaming', 'painting', 'reading'],
    readinessScore: 6,
    gender: 'male',
    genderPreference: ['male', 'female'],
  },
  {
    id: '72',
    name: 'Tina',
    interests: ['coding', 'movies', 'traveling'],
    readinessScore: 7,
    gender: 'female',
    genderPreference: ['male'],
  },
  {
    id: '73',
    name: 'Uri',
    interests: ['gaming', 'hiking', 'music'],
    readinessScore: 5,
    gender: 'male',
    genderPreference: ['male'],
  },
  {
    id: '74',
    name: 'Val',
    interests: ['reading', 'dancing', 'painting'],
    readinessScore: 8,
    gender: 'non-binary',
    genderPreference: ['male', 'female'],
  },
  {
    id: '75',
    name: 'Wade',
    interests: ['music', 'coding', 'traveling'],
    readinessScore: 6,
    gender: 'male',
    genderPreference: ['female'],
  },
  {
    id: '76',
    name: 'Xena',
    interests: ['movies', 'gaming', 'photography'],
    readinessScore: 9,
    gender: 'female',
    genderPreference: ['female'],
  },
  {
    id: '77',
    name: 'Yale',
    interests: ['painting', 'reading', 'music'],
    readinessScore: 7,
    gender: 'male',
    genderPreference: ['male', 'female'],
  },
  {
    id: '78',
    name: 'Zoe',
    interests: ['hiking', 'dancing', 'gaming'],
    readinessScore: 8,
    gender: 'female',
    genderPreference: ['male'],
  },
  {
    id: '79',
    name: 'Adam',
    interests: ['traveling', 'coding', 'movies'],
    readinessScore: 5,
    gender: 'male',
    genderPreference: ['male'],
  },
  {
    id: '80',
    name: 'Bella',
    interests: ['gaming', 'music', 'photography'],
    readinessScore: 6,
    gender: 'female',
    genderPreference: ['male', 'female'],
  },
  {
    id: '81',
    name: 'Caleb',
    interests: ['reading', 'hiking', 'dancing'],
    readinessScore: 7,
    gender: 'male',
    genderPreference: ['female'],
  },
  {
    id: '82',
    name: 'Dana',
    interests: ['music', 'movies', 'coding'],
    readinessScore: 8,
    gender: 'female',
    genderPreference: ['female'],
  },
  {
    id: '83',
    name: 'Eli',
    interests: ['gaming', 'painting', 'traveling'],
    readinessScore: 9,
    gender: 'male',
    genderPreference: ['male', 'female'],
  },
  {
    id: '84',
    name: 'Faye',
    interests: ['hiking', 'reading', 'dancing'],
    readinessScore: 5,
    gender: 'female',
    genderPreference: ['male'],
  },
  {
    id: '85',
    name: 'Gabe',
    interests: ['movies', 'music', 'gaming'],
    readinessScore: 7,
    gender: 'male',
    genderPreference: ['male'],
  },
  {
    id: '86',
    name: 'Holly',
    interests: ['photography', 'traveling', 'coding'],
    readinessScore: 6,
    gender: 'female',
    genderPreference: ['male', 'female'],
  },
  {
    id: '87',
    name: 'Isaac',
    interests: ['reading', 'gaming', 'hiking'],
    readinessScore: 8,
    gender: 'male',
    genderPreference: ['female'],
  },
  {
    id: '88',
    name: 'Jill',
    interests: ['movies', 'dancing', 'painting'],
    readinessScore: 9,
    gender: 'female',
    genderPreference: ['female'],
  },
  {
    id: '89',
    name: 'Karl',
    interests: ['gaming', 'music', 'traveling'],
    readinessScore: 5,
    gender: 'male',
    genderPreference: ['male', 'female'],
  },
  {
    id: '90',
    name: 'Lana',
    interests: ['reading', 'hiking', 'coding'],
    readinessScore: 7,
    gender: 'female',
    genderPreference: ['male'],
  },
  {
    id: '91',
    name: 'Mark',
    interests: ['painting', 'movies', 'gaming'],
    readinessScore: 8,
    gender: 'male',
    genderPreference: ['male'],
  },
  {
    id: '92',
    name: 'Nina',
    interests: ['dancing', 'music', 'traveling'],
    readinessScore: 6,
    gender: 'female',
    genderPreference: ['male', 'female'],
  },
  {
    id: '93',
    name: 'Oscar',
    interests: ['reading', 'gaming', 'hiking'],
    readinessScore: 9,
    gender: 'male',
    genderPreference: ['female'],
  },
  {
    id: '94',
    name: 'Paula',
    interests: ['movies', 'painting', 'music'],
    readinessScore: 7,
    gender: 'female',
    genderPreference: ['female'],
  },
  {
    id: '95',
    name: 'Quinn',
    interests: ['coding', 'gaming', 'traveling'],
    readinessScore: 5,
    gender: 'male',
    genderPreference: ['male', 'female'],
  },
  {
    id: '96',
    name: 'Ruth',
    interests: ['hiking', 'dancing', 'movies'],
    readinessScore: 6,
    gender: 'female',
    genderPreference: ['male'],
  },
  {
    id: '97',
    name: 'Sam',
    interests: ['music', 'reading', 'gaming'],
    readinessScore: 8,
    gender: 'male',
    genderPreference: ['male'],
  },
  {
    id: '98',
    name: 'Tina',
    interests: ['painting', 'traveling', 'coding'],
    readinessScore: 9,
    gender: 'female',
    genderPreference: ['male', 'female'],
  },
  {
    id: '99',
    name: 'Umar',
    interests: ['movies', 'hiking', 'music'],
    readinessScore: 7,
    gender: 'male',
    genderPreference: ['female'],
  },
  {
    id: '100',
    name: 'Vera',
    interests: ['gaming', 'dancing', 'photography'],
    readinessScore: 6,
    gender: 'female',
    genderPreference: ['female'],
  },
]
